# Generated by Django 5.2.10 on 2026-06-13 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_on', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(help_text='Hospital or blood bank where you donated', max_length=255)),
                ('blood_type', models.CharField(max_length=3)),
                ('units', models.DecimalField(decimal_places=1, default=1.0, help_text='Units of blood donated (typically 1 unit = 450ml)', max_digits=4)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin or hospital')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(limit_choices_to={'is_donor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-donated_on'],
            },
        ),
    ]
